package errno

/*
错误码设计
第一位表示错误级别, 1 为系统错误, 2 为普通错误
第二三位表示服务模块代码
第四五位表示具体错误代码
*/

//Server Error
var (
	//serverError: start from 100xx
	Success = NewErrNo(0,"ok")
	ErrUnknown = NewErrNo(10001,"Internal server error,err unknown")
	ErrBind     = NewErrNo(10002, "Error occurred while binding the request body to the struct")
	ErrValidation   = NewErrNo(10003, "Validation failed")
	ErrTokenInvalid = NewErrNo(10004, "Token invalid")
	//database Error:start form 202xx
	ErrDatabase              = NewErrNo(20201, "Database error")
	ErrRecordNotFound        = NewErrNo(20202, "Record not found")
	ErrInvalidTransaction    = NewErrNo(20203, "Invalid transaction when you are trying to `Commit` or `Rollback`")
	ErrNotImplemented        = NewErrNo(20204, "Not implemented")
	ErrMissingWhereClause    = NewErrNo(20205, "Missing where clause")
	ErrUnsupportedRelation   = NewErrNo(20206, "Unsupported relations")
	ErrPrimaryKeyRequired    = NewErrNo(20207, "Primary keys required")
	ErrModelValueRequired    = NewErrNo(20208, "Model value required")
	ErrInvalidData           = NewErrNo(20209, "Unsupported data")
	ErrUnsupportedDriver     = NewErrNo(20210, "Unsupported driver")
	ErrRegistered            = NewErrNo(20211, "Registered")
	ErrInvalidField          = NewErrNo(20212, "Invalid field")
	ErrEmptySlice            = NewErrNo(20213, "Empty slice found")
	ErrDryRunModeUnsupported = NewErrNo(20214, "Dry run mode unsupported")
	ErrInvalidDB             = NewErrNo(20215, "Invalid db")
	ErrInvalidValue          = NewErrNo(20216, "Invalid value")
	ErrInvalidValueOfLength  = NewErrNo(20217, "Invalid values do not match length")
	ErrPreloadNotAllowed     = NewErrNo(20218, "Preload is not allowed when count is used")
	//userPassword Error: start from 201xx
	ErrEncrypt           = NewErrNo(20101, "Error occurred while encrypting the user password")
	ErrSignatureInvalid  = NewErrNo(20102, "Signature is invalid")
	ErrExpired           = NewErrNo(20103, "Token expired")
	ErrInvalidAuthHeader = NewErrNo(20104, "Invalid authorization header")
	ErrMissingHeader     = NewErrNo(20105, "The `Authorization` header was empty")
	ErrorExpired         = NewErrNo(20106, "Token expired")
	ErrPasswordIncorrect = NewErrNo(20107, "Password was incorrect")
	ErrPermissionDenied  = NewErrNo(20108, "Permission denied")
	//编解码错误,encode Error:start from 203xx
	ErrEncodingFailed = NewErrNo(20301, "Encoding failed due to an error with the data")
	ErrDecodingFailed = NewErrNo(20302, "Decoding failed due to an error with the data")
	ErrInvalidJSON    = NewErrNo(20303, "Data is not valid JSON")
	ErrEncodingJSON   = NewErrNo(20304, "JSON data could not be encoded")
	ErrDecodingJSON   = NewErrNo(20305, "JSON data could not be decoded")
	ErrInvalidYaml    = NewErrNo(20306, "Data is not valid Yaml")
	ErrEncodingYaml   = NewErrNo(20307, "Yaml data could not be encoded")
	ErrDecodingYaml   = NewErrNo(20308, "Yaml data could not be decoded")
	//业务上的普通错误
	ErrUserNotFound        = NewErrNo(20401, "User not found")
	ErrUserAlreadyExist    = NewErrNo(20402, "User already exist")
	ErrReachMaxCount       = NewErrNo(20403, "Secret reach the max count")
	ErrSecretNotFound      = NewErrNo(20404, "Secret not found")
	ErrVideoNotFound       = NewErrNo(20405, "Video not found")
	ErrInvalidHash         = NewErrNo(20406, "Encoded hash is not in the correct format")
	ErrIncompatibleVersion = NewErrNo(20407, "Encoded hash is not in the correct format")
)

//Http error
var (
	//Http error:start from 30xxx
	HttpSuccess                  = NewHttpErr(30001, 200, "OK")
	ErrHttpUnknown               = NewHttpErr(30002, 500, "Internal server error")
	ErrHttpBind                  = NewHttpErr(30003, 400, "Error occurred while binding the request body to the struct")
	ErrHttpValidation            = NewHttpErr(30004, 400, "Validation failed")
	ErrHttpTokenInvalid          = NewHttpErr(30005, 401, "Token invalid")
	ErrHttpDatabase              = NewHttpErr(30006, 500, "Database error")
	ErrHttpRecordNotFound        = NewHttpErr(30007, 500, "Record not found")
	ErrHttpInvalidTransaction    = NewHttpErr(30008, 500, "Invalid transaction when you are trying to `Commit` or `Rollback`")
	ErrHttpNotImplemented        = NewHttpErr(30009, 500, "Not implemented")
	ErrHttpMissingWhereClause    = NewHttpErr(30010, 500, "Missing where clause")
	ErrHttpUnsupportedRelation   = NewHttpErr(30011, 500, "Unsupported relations")
	ErrHttpPrimaryKeyRequired    = NewHttpErr(30012, 500, "Primary keys required")
	ErrHttpModelValueRequired    = NewHttpErr(30013, 500, "Model value required")
	ErrHttpInvalidData           = NewHttpErr(30014, 500, "Unsupported data")
	ErrHttpUnsupportedDriver     = NewHttpErr(30015, 500, "Unsupported driver")
	ErrHttpRegistered            = NewHttpErr(30016, 500, "Registered")
	ErrHttpInvalidField          = NewHttpErr(30017, 500, "Invalid field")
	ErrHttpEmptySlice            = NewHttpErr(30018, 500, "Empty slice found")
	ErrHttpDryRunModeUnsupported = NewHttpErr(30019, 500, "Dry run mode unsupported")
	ErrHttpInvalidDB             = NewHttpErr(30020, 500, "Invalid db")
	ErrHttpInvalidValue          = NewHttpErr(30021, 500, "Invalid value")
	ErrHttpInvalidValueOfLength  = NewHttpErr(30022, 500, "Invalid values do not match length")
	ErrHttpPreloadNotAllowed     = NewHttpErr(30023, 500, "Preload is not allowed when count is used")
	ErrHttpEncrypt               = NewHttpErr(30024, 401, "Error occurred while encrypting the user password")
	ErrHttpSignatureInvalid      = NewHttpErr(30025, 401, "Signature is invalid")
	ErrHttpExpired               = NewHttpErr(30026, 401, "Token expired")
	ErrHttpInvalidAuthHeader     = NewHttpErr(30027, 401, "Invalid authorization header")
	ErrHttpMissingHeader         = NewHttpErr(30028, 401, "The `Authorization` header was empty")
	ErrHttporExpired             = NewHttpErr(30029, 401, "Token expired")
	ErrHttpPasswordIncorrect     = NewHttpErr(30030, 401, "Password was incorrect")
	ErrHttpPermissionDenied      = NewHttpErr(30031, 403, "Permission denied")
	ErrHttpEncodingFailed        = NewHttpErr(30032, 500, "Encoding failed due to an error with the data")
	ErrHttpDecodingFailed        = NewHttpErr(30033, 500, "Decoding failed due to an error with the data")
	ErrHttpInvalidJSON           = NewHttpErr(30034, 500, "Data is not valid JSON")
	ErrHttpEncodingJSON          = NewHttpErr(30035, 500, "JSON data could not be encoded")
	ErrHttpDecodingJSON          = NewHttpErr(30036, 500, "JSON data could not be decoded")
	ErrHttpInvalidYaml           = NewHttpErr(30037, 500, "Data is not valid Yaml")
	ErrHttpEncodingYaml          = NewHttpErr(30038, 500, "Yaml data could not be encoded")
	ErrHttpDecodingYaml          = NewHttpErr(30039, 500, "Yaml data could not be decoded")
	ErrHttpUserNotFound          = NewHttpErr(30040, 404, "User not found")
	ErrHttpUserAlreadyExist      = NewHttpErr(30041, 400, "User already exist")
	ErrHttpReachMaxCount         = NewHttpErr(30042, 400, "Secret reach the max count")
	ErrHttpSecretNotFound        = NewHttpErr(30043, 404, "Secret not found")
	ErrHttpVideoNotFound         = NewHttpErr(30044, 400, "Video not found")
	ErrHttpInvalidHash           = NewHttpErr(30045, 500, "Encoded hash is not in the correct format")
	ErrHttpIncompatibleVersion   = NewHttpErr(30046, 500, "Encoded hash is not in the correct format")
)

